name: Check pull request
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run_tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      - &checkout_step
        name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        run: make test

  license_validation:
    needs: [run_tests]
    name: "Validate that license added to all files"
    runs-on: ubuntu-latest

    steps:
      - *checkout_step
      - name: Setup Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version: '1.25.x'
      - name: Run validation
        run: make validation/license

  lint:
    needs: [run_tests, license_validation]
    name: "Lint golang code"
    runs-on: ubuntu-latest

    steps:
      - *checkout_step
      - name: Run lint
        run: make lint